language: php

php:
  - 7.1

services:
  - docker

before_install:
  - ls -d docker/data/* | grep -v .gitignore | xargs rm -rf
  - docker build -f docker/Dockerfile --tag lamp:travis docker
  - sleep 15
  - docker run -d --name lamp -v `pwd`:/var/www/html -p 38401:80 lamp:travis

install:
  - composer self-update
  - travis_retry composer install --no-interaction --no-scripts --prefer-source

before_script:
  - TRAVIS=true
  - cp .env.example .env
  - php artisan key:generate
  - docker exec -it lamp chmod -R 777 /var/www/html/storage
  - docker exec -it lamp bash /refresh_mysql_pid.sh

script:
  - vendor/bin/phpunit
  - docker container ls
  - curl -s -XGET http://localhost:38401/health
  - docker exec -it lamp mysql -e "SELECT 1;"

matrix:
  fast_finish: true
